[package]

name = "img_hash"
version = "2.1.0"
authors = ["Austin Bonander <austin.bonander@gmail.com>"]

description = "A simple library that provides perceptual hashing and difference calculation for images."

license = "MIT OR Apache-2.0"

documentation = "http://docs.rs/img_hash"

keywords = ["image", "hash", "perceptual", "difference"]

repository = "http://github.com/abonander/img_hash"

[features]
default = ["rust-image"]
rust-image = ["image"]
serialize = ["serde", "bit-vec/serde"]
bench = []

[dependencies]
bit-vec = "0.6"

[dev-dependencies]
rand = "0.3"
image = ">=0.10, <=0.19"
bincode = "1.1"
bit-vec = { version = "0.6", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }

[dependencies.image]
version = ">=0.10, <=0.19"
optional = true

[dependencies.serde]
version = "1.0"
features = ["derive"]
optional = true
