[package]

name = "img_hash"
version = "3.0.0-alpha.1"
authors = ["Austin Bonander <austin.bonander@gmail.com>"]

description = "A simple library that provides perceptual hashing and difference calculation for images."

license = "MIT OR Apache-2.0"

documentation = "http://docs.rs/img_hash"

keywords = ["image", "hash", "perceptual", "difference"]

repository = "http://github.com/abonander/img_hash"

edition = "2015"

[features]
bench = []
nightly = []
demo = ["interpolation", "rayon"]

[dependencies]
base64 = "0.10"
image = "0.20"
rustdct = "0.3"
serde = { version = "1.0", features = ["derive"] }
transpose = "0.1"

# used in src/bin/demo_*.rs
interpolation = { version = "0.1", optional = true }
rayon = { version = "1.0", optional = true }

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "byte_to_float"
harness = false

[[bin]]
name = "demo_gradient"
required-features = ["demo"]
