[package]

name = "img_hash"
version = "3.0.0-alpha.1"
authors = ["Austin Bonander <austin.bonander@gmail.com>"]

description = "A simple library that provides perceptual hashing and difference calculation for images."

license = "MIT OR Apache-2.0"

documentation = "http://docs.rs/img_hash"

keywords = ["image", "hash", "perceptual", "difference"]

repository = "http://github.com/abonander/img_hash"

edition = "2015"

[features]
bench = []
nightly = []

[dependencies]
base64 = "0.10"
image = "0.20"
num-traits = "0.2"
serde = { version = "1.0", features = ["derive"] }

